services:
  tibero-db:
    container_name: tibero-db
    image: ghcr.io/bob-park/tibero6
    hostname: malgn-dev-tibero
    ports:
      - 8629:8629
    volumes:
      - ./tibero/database:/home/tibero/tibero6/database
      - ./tibero/init/:/home/tibero/tibero6/instance/tibero
      - ./tibero/license:/home/tibero/tibero6/license